// Copyright (c) 2025 Gladstone Joy. Licensed under the MIT License.
package com.example.data.export

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Rect
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import com.example.data.security.SafeLog as Log
import com.example.domain.ai.BudgetAiResult
import com.example.domain.analytics.GoalAnalysis
import com.example.domain.model.Transaction
import com.example.presentation.ui.UiUtils
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

class PdfExportService {
    private val tag = "PdfExportService"

    // PageCursor tracks dynamic vertical layout and handles auto-generation of pages.
    private class PageCursor(
        private val pdfDocument: PdfDocument,
        val width: Int = 595, // A4 standard width at 72dpi
        val height: Int = 842, // A4 standard height at 72dpi
        val margin: Float = 40f,
        val lang: com.example.ui.localization.AppLanguageSupported = com.example.presentation.ui.UiUtils.currentLanguage
    ) {
        var pageNumber = 1
            private set
        var currentPage: PdfDocument.Page? = null
            private set
        var canvas: Canvas? = null
            private set
        var currentY = margin
            private set

        init {
            startNewPage()
        }

        fun startNewPage() {
            if (currentPage != null) {
                drawFooter()
                pdfDocument.finishPage(currentPage)
            }
            val pageInfo = PdfDocument.PageInfo.Builder(width, height, pageNumber).create()
            currentPage = pdfDocument.startPage(pageInfo)
            canvas = currentPage!!.canvas
            currentY = margin
            drawHeader()
            pageNumber++
        }

        private fun drawHeader() {
            val c = canvas ?: return
            if (pageNumber > 1) {
                // Subtle gray lines on follow-up pages
                val p = Paint().apply {
                    color = Color.parseColor("#E0E0E0")
                    strokeWidth = 1f
                    style = Paint.Style.STROKE
                }
                c.drawLine(margin, margin - 10f, width - margin, margin - 10f, p)

                val textPaint = Paint().apply {
                    color = Color.parseColor("#757575")
                    textSize = 8f
                    isAntiAlias = true
                    typeface = Typeface.create(Typeface.DEFAULT, Typeface.ITALIC)
                }
                val headerText = when (lang) {
                    com.example.ui.localization.AppLanguageSupported.ENGLISH -> "Budget Joy Report (continued)"
                    com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "Budget Joy Bericht (Fortsetzung)"
                    com.example.ui.localization.AppLanguageSupported.ESPANOL -> "Informe Budget Joy (continuación)"
                    com.example.ui.localization.AppLanguageSupported.ITALIANO -> "Rapporto Budget Joy (continua)"
                    com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "Relatório Budget Joy (continuação)"
                    com.example.ui.localization.AppLanguageSupported.CHINESE -> "Budget Joy 报告 (续)"
                    com.example.ui.localization.AppLanguageSupported.JAPANESE -> "Budget Joy レポート (続き)"
                    com.example.ui.localization.AppLanguageSupported.KOREAN -> "Budget Joy 보고서 (계속)"
                    com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "Отчет Budget Joy (продолжение)"
                    com.example.ui.localization.AppLanguageSupported.ARABIC -> "تقرير Budget Joy (متابع)"
                    else -> "Rapport Budget Joy (suite)"
                }
                c.drawText(headerText, margin, margin - 15f, textPaint)
                currentY = margin + 10f
            }
        }

        private fun drawFooter() {
            val c = canvas ?: return
            val p = Paint().apply {
                color = Color.parseColor("#E0E0E0")
                strokeWidth = 1f
                style = Paint.Style.STROKE
            }
            c.drawLine(margin, height - margin + 10f, width - margin, height - margin + 10f, p)

            val textPaint = Paint().apply {
                color = Color.parseColor("#757575")
                textSize = 8f
                isAntiAlias = true
            }
            val footerText = when (lang) {
                com.example.ui.localization.AppLanguageSupported.ENGLISH -> "Generated by Budget Joy"
                com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "Generiert von Budget Joy"
                com.example.ui.localization.AppLanguageSupported.ESPANOL -> "Generado por Budget Joy"
                com.example.ui.localization.AppLanguageSupported.ITALIANO -> "Generato da Budget Joy"
                com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "Gerado por Budget Joy"
                com.example.ui.localization.AppLanguageSupported.CHINESE -> "由 Budget Joy 生成"
                com.example.ui.localization.AppLanguageSupported.JAPANESE -> "Budget Joy によって生成"
                com.example.ui.localization.AppLanguageSupported.KOREAN -> "Budget Joy에 의해 생성됨"
                com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "Создано в Budget Joy"
                com.example.ui.localization.AppLanguageSupported.ARABIC -> "تم الإنشاء بواسطة Budget Joy"
                else -> "Généré par Budget Joy"
            }
            c.drawText(footerText, margin, height - margin + 22f, textPaint)

            val pageLabel = when (lang) {
                com.example.ui.localization.AppLanguageSupported.ENGLISH -> "Page"
                com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "Seite"
                com.example.ui.localization.AppLanguageSupported.ESPANOL -> "Página"
                com.example.ui.localization.AppLanguageSupported.ITALIANO -> "Pagina"
                com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "Página"
                com.example.ui.localization.AppLanguageSupported.CHINESE -> "页"
                com.example.ui.localization.AppLanguageSupported.JAPANESE -> "ページ"
                com.example.ui.localization.AppLanguageSupported.KOREAN -> "페이지"
                com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "Страница"
                com.example.ui.localization.AppLanguageSupported.ARABIC -> "صفحة"
                else -> "Page"
            }
            val pageStr = "$pageLabel ${pageNumber - 1}"
            val bounds = Rect()
            textPaint.getTextBounds(pageStr, 0, pageStr.length, bounds)
            c.drawText(pageStr, width - margin - bounds.width(), height - margin + 22f, textPaint)
        }

        fun ensureSpace(heightNeeded: Float) {
            if (currentY + heightNeeded > height - margin) {
                startNewPage()
            }
        }

        fun moveDown(dy: Float) {
            currentY += dy
        }

        fun finish() {
            if (currentPage != null) {
                drawFooter()
                pdfDocument.finishPage(currentPage)
                currentPage = null
                canvas = null
            }
        }
    }

    /**
     * Generates a beautifully formatted PDF document into the cache directory.
     */
    fun generatePdf(
        context: Context,
        userEmail: String?,
        totalIncome: Double,
        totalExpense: Double,
        totalSaving: Double,
        balance: Double,
        savingsRate: Double,
        budgetStatus: String,
        goals: List<GoalAnalysis>,
        aiResult: BudgetAiResult?,
        transactions: List<Transaction>
    ): File? {
        Log.d(tag, "Generating budget PDF report...")
        val lang = com.example.presentation.ui.UiUtils.currentLanguage
        val pdfDocument = PdfDocument()
        val cursor = PageCursor(pdfDocument, lang = lang)

        try {
            // General reusable paints
            val titlePaint = Paint().apply {
                color = Color.parseColor("#1A237E") // Deep Indigo Accent
                textSize = 20f
                typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                isAntiAlias = true
            }

            val subtitlePaint = Paint().apply {
                color = Color.parseColor("#3F51B5")
                textSize = 10f
                typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                isAntiAlias = true
            }

            val sectionHeadPaint = Paint().apply {
                color = Color.parseColor("#1A237E")
                textSize = 12f
                typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                isAntiAlias = true
            }

            val normalPaint = Paint().apply {
                color = Color.parseColor("#212121")
                textSize = 9f
                typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
                isAntiAlias = true
            }

            val boldPaint = Paint().apply {
                color = Color.parseColor("#212121")
                textSize = 9f
                typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                isAntiAlias = true
            }

            val grayPaint = Paint().apply {
                color = Color.parseColor("#616161")
                textSize = 8.5f
                isAntiAlias = true
            }

            val linePaint = Paint().apply {
                color = Color.parseColor("#D0D0D0")
                strokeWidth = 1f
                style = Paint.Style.STROKE
            }

            // --- HEADER ---
            cursor.ensureSpace(80f)
            val t = com.example.ui.localization.getStringsForLanguage(lang)
            val pdfLocale = when (lang) {
                com.example.ui.localization.AppLanguageSupported.FRANCAIS -> Locale.FRANCE
                com.example.ui.localization.AppLanguageSupported.ENGLISH -> Locale.US
                com.example.ui.localization.AppLanguageSupported.ESPANOL -> Locale("es", "ES")
                com.example.ui.localization.AppLanguageSupported.DEUTSCH -> Locale.GERMANY
                com.example.ui.localization.AppLanguageSupported.ITALIANO -> Locale.ITALY
                com.example.ui.localization.AppLanguageSupported.PORTUGUES -> Locale("pt", "PT")
                com.example.ui.localization.AppLanguageSupported.CHINESE -> Locale.CHINA
                com.example.ui.localization.AppLanguageSupported.JAPANESE -> Locale.JAPAN
                com.example.ui.localization.AppLanguageSupported.ARABIC -> Locale("ar", "SA")
                com.example.ui.localization.AppLanguageSupported.RUSSIAN -> Locale("ru", "RU")
                com.example.ui.localization.AppLanguageSupported.KOREAN -> Locale.KOREA
            }

            val reportTitle = when (lang) {
                com.example.ui.localization.AppLanguageSupported.ENGLISH -> "Budget Joy Report"
                com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "Budget Joy Bericht"
                com.example.ui.localization.AppLanguageSupported.ESPANOL -> "Informe Budget Joy"
                com.example.ui.localization.AppLanguageSupported.ITALIANO -> "Rapporto Budget Joy"
                com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "Relatório Budget Joy"
                com.example.ui.localization.AppLanguageSupported.CHINESE -> "Budget Joy 财务报告"
                com.example.ui.localization.AppLanguageSupported.JAPANESE -> "Budget Joy レポート"
                com.example.ui.localization.AppLanguageSupported.KOREAN -> "Budget Joy 보고서"
                com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "Отчет Budget Joy"
                com.example.ui.localization.AppLanguageSupported.ARABIC -> "تقرير Budget Joy"
                else -> "Rapport Budget Joy"
            }
            cursor.canvas?.drawText(reportTitle, cursor.margin, cursor.currentY, titlePaint)
            cursor.moveDown(18f)

            val currentMonthRaw = SimpleDateFormat("MMMM yyyy", pdfLocale).format(Date())
            val currentMonth = if (currentMonthRaw.isNotEmpty()) currentMonthRaw.replaceFirstChar { it.uppercase() } else currentMonthRaw
            val generationDate = SimpleDateFormat("dd/MM/yyyy HH:mm", pdfLocale).format(Date())

            val subReportLabel = when (lang) {
                com.example.ui.localization.AppLanguageSupported.ENGLISH -> "MONTHLY REPORT • $currentMonth"
                com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "MONATSBERICHT • $currentMonth"
                com.example.ui.localization.AppLanguageSupported.ESPANOL -> "INFORME MENSUAL • $currentMonth"
                com.example.ui.localization.AppLanguageSupported.ITALIANO -> "RAPPORTO MENSILE • $currentMonth"
                com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "RELATÓRIO MENSAL • $currentMonth"
                com.example.ui.localization.AppLanguageSupported.CHINESE -> "月度财务报告 • $currentMonth"
                com.example.ui.localization.AppLanguageSupported.JAPANESE -> "月間レポート • $currentMonth"
                com.example.ui.localization.AppLanguageSupported.KOREAN -> "월간 보고서 • $currentMonth"
                com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "ЕЖЕМЕСЯЧНЫЙ ОТЧЕТ • $currentMonth"
                com.example.ui.localization.AppLanguageSupported.ARABIC -> "التقرير الشهري • $currentMonth"
                else -> "RAPPORT MENSUEL • $currentMonth"
            }
            cursor.canvas?.drawText(subReportLabel, cursor.margin, cursor.currentY, subtitlePaint)
            cursor.moveDown(15f)

            val genDateLabel = when (lang) {
                com.example.ui.localization.AppLanguageSupported.ENGLISH -> "Generated on: "
                com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "Generiert am: "
                com.example.ui.localization.AppLanguageSupported.ESPANOL -> "Generado el: "
                com.example.ui.localization.AppLanguageSupported.ITALIANO -> "Generato il: "
                com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "Gerado em: "
                com.example.ui.localization.AppLanguageSupported.CHINESE -> "生成时间："
                com.example.ui.localization.AppLanguageSupported.JAPANESE -> "生成日時："
                com.example.ui.localization.AppLanguageSupported.KOREAN -> "생성일："
                com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "Создано: "
                com.example.ui.localization.AppLanguageSupported.ARABIC -> "تم الإنشاء في: "
                else -> "Généré le : "
            }
            cursor.canvas?.drawText("$genDateLabel$generationDate", cursor.margin, cursor.currentY, grayPaint)
            
            val userEmailLabel = when (lang) {
                com.example.ui.localization.AppLanguageSupported.ENGLISH -> "User: "
                com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "Benutzer: "
                com.example.ui.localization.AppLanguageSupported.ESPANOL -> "Usuario: "
                com.example.ui.localization.AppLanguageSupported.ITALIANO -> "Utente: "
                com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "Usuário: "
                com.example.ui.localization.AppLanguageSupported.CHINESE -> "用户："
                com.example.ui.localization.AppLanguageSupported.JAPANESE -> "ユーザー："
                com.example.ui.localization.AppLanguageSupported.KOREAN -> "사용자："
                com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "Пользователь: "
                com.example.ui.localization.AppLanguageSupported.ARABIC -> "المستخدم: "
                else -> "Email utilisateur : "
            }
            if (!userEmail.isNullOrBlank()) {
                val emailText = "$userEmailLabel$userEmail"
                val emailWidth = grayPaint.measureText(emailText)
                cursor.canvas?.drawText(emailText, cursor.width - cursor.margin - emailWidth, cursor.currentY, grayPaint)
            }
            cursor.moveDown(10f)

            // Divider line
            cursor.canvas?.drawLine(cursor.margin, cursor.currentY, cursor.width - cursor.margin, cursor.currentY, linePaint)
            cursor.moveDown(15f)

            // --- SECTION 1: FINANCIAL SUMMARY ---
            cursor.ensureSpace(90f)
            val secFinSummary = when (lang) {
                com.example.ui.localization.AppLanguageSupported.ENGLISH -> "MONTHLY FINANCIAL OVERVIEW"
                com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "FINANZÜBERSICHT DES MONATS"
                com.example.ui.localization.AppLanguageSupported.ESPANOL -> "RESUMEN FINANCIERO MENSUAL"
                com.example.ui.localization.AppLanguageSupported.ITALIANO -> "RIEPILOGO FINANZIARIO MENSILE"
                com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "RESUMO FINANCEIRO DO MÊS"
                com.example.ui.localization.AppLanguageSupported.CHINESE -> "本月财务摘要"
                com.example.ui.localization.AppLanguageSupported.JAPANESE -> "当月の財務概要"
                com.example.ui.localization.AppLanguageSupported.KOREAN -> "당월 재정 요약"
                com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "ФИНАНСОВЫЙ ОТЧЕТ ЗА МЕСЯЦ"
                com.example.ui.localization.AppLanguageSupported.ARABIC -> "الملخص المالي للشهر"
                else -> "RÉSUMÉ FINANCIER DU MOIS"
            }
            cursor.canvas?.drawText(secFinSummary, cursor.margin, cursor.currentY, sectionHeadPaint)
            cursor.moveDown(15f)

            // Table of values (Income, Expenses, Savings, Balance)
            val boxWidth = (cursor.width - cursor.margin * 2f) / 4f
            val startX = cursor.margin

            val incomeLabel = when (lang) {
                com.example.ui.localization.AppLanguageSupported.ENGLISH -> "Total Income"
                com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "Einnahmen Gesamt"
                com.example.ui.localization.AppLanguageSupported.ESPANOL -> "Ingresos Totales"
                com.example.ui.localization.AppLanguageSupported.ITALIANO -> "Entrate Totali"
                com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "Total de Receitas"
                com.example.ui.localization.AppLanguageSupported.CHINESE -> "总收入"
                com.example.ui.localization.AppLanguageSupported.JAPANESE -> "収入合計"
                com.example.ui.localization.AppLanguageSupported.KOREAN -> "총 수입"
                com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "Всего доходов"
                com.example.ui.localization.AppLanguageSupported.ARABIC -> "إجمالي الدخل"
                else -> "Total " + t.income
            }

            val expenseLabel = when (lang) {
                com.example.ui.localization.AppLanguageSupported.ENGLISH -> "Total Expenses"
                com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "Ausgaben Gesamt"
                com.example.ui.localization.AppLanguageSupported.ESPANOL -> "Gastos Totales"
                com.example.ui.localization.AppLanguageSupported.ITALIANO -> "Uscite Totali"
                com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "Total de Despesas"
                com.example.ui.localization.AppLanguageSupported.CHINESE -> "总支出"
                com.example.ui.localization.AppLanguageSupported.JAPANESE -> "支出合計"
                com.example.ui.localization.AppLanguageSupported.KOREAN -> "총 지출"
                com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "Всего расходов"
                com.example.ui.localization.AppLanguageSupported.ARABIC -> "إجمالي المصاريف"
                else -> "Total " + t.expense
            }

            val savingLabel = when (lang) {
                com.example.ui.localization.AppLanguageSupported.ENGLISH -> "Total Savings"
                com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "Ersparnisse Gesamt"
                com.example.ui.localization.AppLanguageSupported.ESPANOL -> "Total de Ahorros"
                com.example.ui.localization.AppLanguageSupported.ITALIANO -> "Risparmi Totali"
                com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "Total de Poupança"
                com.example.ui.localization.AppLanguageSupported.CHINESE -> "总储蓄"
                com.example.ui.localization.AppLanguageSupported.JAPANESE -> "貯蓄合計"
                com.example.ui.localization.AppLanguageSupported.KOREAN -> "총 저축"
                com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "Всего сбережений"
                com.example.ui.localization.AppLanguageSupported.ARABIC -> "إجمالي الادخار"
                else -> "Total " + t.saving
            }

            val balanceLabel = when (lang) {
                com.example.ui.localization.AppLanguageSupported.ENGLISH -> "Available Balance"
                com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "Verfügbares Guthaben"
                com.example.ui.localization.AppLanguageSupported.ESPANOL -> "Saldo Disponible"
                com.example.ui.localization.AppLanguageSupported.ITALIANO -> "Saldo Disponibile"
                com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "Saldo Disponível"
                com.example.ui.localization.AppLanguageSupported.CHINESE -> "可用余额"
                com.example.ui.localization.AppLanguageSupported.JAPANESE -> "利用可能残高"
                com.example.ui.localization.AppLanguageSupported.KOREAN -> "사용 가능한 잔액"
                com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "Доступный баланс"
                com.example.ui.localization.AppLanguageSupported.ARABIC -> "الرصيد المتاح"
                else -> t.availableBalance
            }

            val sums = listOf(
                Triple(incomeLabel, totalIncome, "#2E7D32"), // Green
                Triple(expenseLabel, totalExpense, "#C62828"), // Red
                Triple(savingLabel, totalSaving, "#1565C0"), // Blue
                Triple(balanceLabel, balance, if (balance >= 0) "#1A237E" else "#C62828")
            )

            val boxPaint = Paint().apply {
                style = Paint.Style.FILL
            }
            val boxBorderPaint = Paint().apply {
                color = Color.parseColor("#E0E0E0")
                strokeWidth = 1f
                style = Paint.Style.STROKE
            }

            sums.forEachIndexed { index, triple ->
                val rx = startX + index * boxWidth
                val topY = cursor.currentY
                val bottomY = cursor.currentY + 45f

                // Light background for cards
                boxPaint.color = Color.parseColor("#F5F5F7")
                cursor.canvas?.drawRect(rx, topY, rx + boxWidth - 5f, bottomY, boxPaint)
                cursor.canvas?.drawRect(rx, topY, rx + boxWidth - 5f, bottomY, boxBorderPaint)

                // Label
                val lblPaint = Paint().apply {
                    color = Color.parseColor("#616161")
                    textSize = 7.5f
                    typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                    isAntiAlias = true
                }
                val labelWidth = lblPaint.measureText(triple.first)
                cursor.canvas?.drawText(
                    triple.first,
                    rx + (boxWidth - 5f - labelWidth) / 2f,
                    topY + 16f,
                    lblPaint
                )

                // Value
                val valPaint = Paint().apply {
                    color = Color.parseColor(triple.third)
                    textSize = 9.5f
                    typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                    isAntiAlias = true
                }
                val valText = UiUtils.formatCurrency(triple.second)
                val valWidth = valPaint.measureText(valText)
                cursor.canvas?.drawText(
                    valText,
                    rx + (boxWidth - 5f - valWidth) / 2f,
                    topY + 34f,
                    valPaint
                )
            }
            cursor.moveDown(60f)

            // --- SECTION 2: METRIC ANALYSIS ---
            cursor.ensureSpace(80f)
            val ratioAnalysisTitle = when (lang) {
                com.example.ui.localization.AppLanguageSupported.ENGLISH -> "RATIO ANALYSIS"
                com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "RATIO-ANALYSE"
                com.example.ui.localization.AppLanguageSupported.ESPANOL -> "ANÁLISIS DE RATIOS"
                com.example.ui.localization.AppLanguageSupported.ITALIANO -> "ANALISI DEI RATIO"
                com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "ANÁLISE DE PROPORÇÕES"
                com.example.ui.localization.AppLanguageSupported.CHINESE -> "比率分析"
                com.example.ui.localization.AppLanguageSupported.JAPANESE -> "比率分析"
                com.example.ui.localization.AppLanguageSupported.KOREAN -> "비율 분석"
                com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "АНАЛИЗ КОЭФФИЦИЕНТОВ"
                com.example.ui.localization.AppLanguageSupported.ARABIC -> "تحليل النسب"
                else -> "ANALYSE DES RATIOS"
            }
            cursor.canvas?.drawText(ratioAnalysisTitle, cursor.margin, cursor.currentY, sectionHeadPaint)
            cursor.moveDown(15f)

            // Display interesting stats (Ratio Dépenses/Revenus, Ratio Épargne/Revenus, Statut financier)
            val expenseRatio = if (totalIncome > 0.0) (totalExpense / totalIncome) * 100 else 0.0
            val savingsRatio = if (totalIncome > 0.0) (totalSaving / totalIncome) * 100 else 0.0

            val expenseRatioLabel = when (lang) {
                com.example.ui.localization.AppLanguageSupported.ENGLISH -> "Expenses / Income Ratio:"
                com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "Ausgaben- / Einnahmen-Verhältnis:"
                com.example.ui.localization.AppLanguageSupported.ESPANOL -> "Ratio Gastos / Ingresos:"
                com.example.ui.localization.AppLanguageSupported.ITALIANO -> "Rapporto Spese / Entrate:"
                com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "Razão Despesas / Receitas:"
                com.example.ui.localization.AppLanguageSupported.CHINESE -> "支出 / 收入比率："
                com.example.ui.localization.AppLanguageSupported.JAPANESE -> "支出 / 収入比率："
                com.example.ui.localization.AppLanguageSupported.KOREAN -> "지출 / 수입 비율："
                com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "Отношение расходов к доходам:"
                com.example.ui.localization.AppLanguageSupported.ARABIC -> "نسبة المصاريف / الدخل:"
                else -> "Ratio Dépenses / Revenus :"
            }
            cursor.canvas?.drawText(expenseRatioLabel, cursor.margin, cursor.currentY, normalPaint)
            cursor.canvas?.drawText(String.format(pdfLocale, "%.1f %%", expenseRatio), cursor.margin + 175f, cursor.currentY, boldPaint)
            cursor.moveDown(12f)

            val savingsRatioLabel = when (lang) {
                com.example.ui.localization.AppLanguageSupported.ENGLISH -> "Savings / Income Ratio:"
                com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "Spar- / Einnahmen-Verhältnis:"
                com.example.ui.localization.AppLanguageSupported.ESPANOL -> "Ratio Ahorros / Ingresos:"
                com.example.ui.localization.AppLanguageSupported.ITALIANO -> "Rapporto Risparmi / Entrate:"
                com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "Razão Poupança / Receitas:"
                com.example.ui.localization.AppLanguageSupported.CHINESE -> "储蓄 / 收入比率："
                com.example.ui.localization.AppLanguageSupported.JAPANESE -> "貯蓄 / 収入比率："
                com.example.ui.localization.AppLanguageSupported.KOREAN -> "저축 / 수입 비율："
                com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "Отношение сбережений к доходам:"
                com.example.ui.localization.AppLanguageSupported.ARABIC -> "نسبة الادخار / الدخل:"
                else -> "Ratio Épargne / Revenus :"
            }
            cursor.canvas?.drawText(savingsRatioLabel, cursor.margin, cursor.currentY, normalPaint)
            cursor.canvas?.drawText(String.format(pdfLocale, "%.1f %%", savingsRatio), cursor.margin + 175f, cursor.currentY, boldPaint)
            cursor.moveDown(12f)

            val statusLabel = when (lang) {
                com.example.ui.localization.AppLanguageSupported.ENGLISH -> "Financial Status & Balance:"
                com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "Finanzstatus & Guthaben:"
                com.example.ui.localization.AppLanguageSupported.ESPANOL -> "Estado y equilibrio financiero:"
                com.example.ui.localization.AppLanguageSupported.ITALIANO -> "Stato finanziario e bilancio:"
                com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "Status e equilíbrio financeiro:"
                com.example.ui.localization.AppLanguageSupported.CHINESE -> "财务状况与平衡："
                com.example.ui.localization.AppLanguageSupported.JAPANESE -> "財務状況と残高："
                com.example.ui.localization.AppLanguageSupported.KOREAN -> "재정 상태 및 균형："
                com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "Финансовое положение и баланс:"
                com.example.ui.localization.AppLanguageSupported.ARABIC -> "الوضع المالي والتوازن:"
                else -> "Statut & Équilibre financier :"
            }
            cursor.canvas?.drawText(statusLabel, cursor.margin, cursor.currentY, normalPaint)
            cursor.canvas?.drawText(budgetStatus, cursor.margin + 175f, cursor.currentY, boldPaint)
            cursor.moveDown(18f)

            // Divider
            cursor.canvas?.drawLine(cursor.margin, cursor.currentY, cursor.width - cursor.margin, cursor.currentY, linePaint)
            cursor.moveDown(15f)

            // --- SECTION 3: SAVINGS GOALS ---
            if (goals.isNotEmpty()) {
                cursor.ensureSpace(goals.size * 50f + 25f)
                val activeGoalsTitle = when (lang) {
                    com.example.ui.localization.AppLanguageSupported.ENGLISH -> "ACTIVE SAVINGS GOALS"
                    com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "AKTIVE SPARZIELE"
                    com.example.ui.localization.AppLanguageSupported.ESPANOL -> "OBJETIVOS DE AHORRO ACTIVOS"
                    com.example.ui.localization.AppLanguageSupported.ITALIANO -> "OBIETTIVI DI RISPARMIO ATTIVI"
                    com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "METAS DE POUPANÇA ATIVAS"
                    com.example.ui.localization.AppLanguageSupported.CHINESE -> "进行中的储蓄目标"
                    com.example.ui.localization.AppLanguageSupported.JAPANESE -> "進行中の貯蓄目標"
                    com.example.ui.localization.AppLanguageSupported.KOREAN -> "진행 중인 저축 목표"
                    com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "АКТИВНЫЕ ЦЕЛИ СБЕРЕЖЕНИЙ"
                    com.example.ui.localization.AppLanguageSupported.ARABIC -> "أهداف الادخار النشطة"
                    else -> "OBJECTIFS D'ÉPARGNE ACTIFS"
                }
                cursor.canvas?.drawText(activeGoalsTitle, cursor.margin, cursor.currentY, sectionHeadPaint)
                cursor.moveDown(15f)

                goals.forEach { goalAnalysis ->
                    cursor.ensureSpace(45f)
                    val goal = goalAnalysis.goal
                    cursor.canvas?.drawText(goal.name, cursor.margin, cursor.currentY, boldPaint)
                    
                    val pct = String.format(pdfLocale, "%.0f%%", goalAnalysis.progressPercentage)
                    val progressText = "${UiUtils.formatCurrency(goalAnalysis.currentCollected)} / ${UiUtils.formatCurrency(goal.targetAmount)} ($pct)"
                    val textWidth = normalPaint.measureText(progressText)
                    cursor.canvas?.drawText(progressText, cursor.width - cursor.margin - textWidth, cursor.currentY, normalPaint)
                    cursor.moveDown(12f)

                    // Draw a micro progress bar
                    val barStartX = cursor.margin
                    val barWidth = cursor.width - cursor.margin * 2f
                    val barHeight = 4f
                    val filledWidth = barWidth * (goalAnalysis.progressPercentage.toFloat() / 100f).coerceIn(0f, 1f)
                    
                    val bgBarPaint = Paint().apply {
                        color = Color.parseColor("#E0E0E0")
                        style = Paint.Style.FILL
                    }
                    val fgBarPaint = Paint().apply {
                        color = Color.parseColor("#1565C0")
                        style = Paint.Style.FILL
                    }
                    cursor.canvas?.drawRect(barStartX, cursor.currentY, barStartX + barWidth, cursor.currentY + barHeight, bgBarPaint)
                    cursor.canvas?.drawRect(barStartX, cursor.currentY, barStartX + filledWidth, cursor.currentY + barHeight, fgBarPaint)
                    cursor.moveDown(10f)

                    // Remaining text & Projection Text
                    val remainingToSaveLabel = when (lang) {
                        com.example.ui.localization.AppLanguageSupported.ENGLISH -> "Remaining to save: "
                        com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "Noch zu sparen: "
                        com.example.ui.localization.AppLanguageSupported.ESPANOL -> "Restante por ahorrar: "
                        com.example.ui.localization.AppLanguageSupported.ITALIANO -> "Rimanente da risparmiare: "
                        com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "Falta poupar: "
                        com.example.ui.localization.AppLanguageSupported.CHINESE -> "剩余需储蓄："
                        com.example.ui.localization.AppLanguageSupported.JAPANESE -> "残りの貯蓄額："
                        com.example.ui.localization.AppLanguageSupported.KOREAN -> "남은 저축액："
                        com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "Осталось сберечь: "
                        com.example.ui.localization.AppLanguageSupported.ARABIC -> "المتبقي للادخار: "
                        else -> "Reste à épargner : "
                    }
                    val leftText = "$remainingToSaveLabel${UiUtils.formatCurrency(goalAnalysis.remainingAmount)}"
                    cursor.canvas?.drawText(leftText, cursor.margin, cursor.currentY, grayPaint)

                    val rightText = goalAnalysis.projectionMessage
                    val rightWidth = grayPaint.measureText(rightText)
                    cursor.canvas?.drawText(rightText, cursor.width - cursor.margin - rightWidth, cursor.currentY, grayPaint)
                    cursor.moveDown(18f)
                }

                // Divider
                cursor.canvas?.drawLine(cursor.margin, cursor.currentY, cursor.width - cursor.margin, cursor.currentY, linePaint)
                cursor.moveDown(15f)
            }

            // --- SECTION 4: AI COACH JOY ADVICE ---
            if (aiResult != null) {
                cursor.ensureSpace(120f)
                val aiSectionTitle = when (lang) {
                    com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "JOY RATGEBER (KI-COACH)"
                    com.example.ui.localization.AppLanguageSupported.ENGLISH -> "JOY ADVICE (AI COACH)"
                    com.example.ui.localization.AppLanguageSupported.ESPANOL -> "CONSEJO DE JOY (AI COACH)"
                    com.example.ui.localization.AppLanguageSupported.ITALIANO -> "CONSIGLI DI JOY (AI COACH)"
                    com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "CONSELHO DA JOY (AI COACH)"
                    com.example.ui.localization.AppLanguageSupported.CHINESE -> "JOY 智能 AI 建议 (智能教练)"
                    com.example.ui.localization.AppLanguageSupported.JAPANESE -> "JOY AIのアドバイス (AIコーチ)"
                    com.example.ui.localization.AppLanguageSupported.KOREAN -> "JOY AI 재정 어드바이스 (AI코치)"
                    com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "РЕКОМЕНДАЦИИ JOY AI (AI COACH)"
                    com.example.ui.localization.AppLanguageSupported.ARABIC -> "نصائح جيو من رفيق الذكاء الاصطناعي JOY"
                    else -> "CONSEIL DE JOY (AI COACH)"
                }
                cursor.canvas?.drawText(aiSectionTitle, cursor.margin, cursor.currentY, sectionHeadPaint)
                
                // Gemini vs local fallback indicator badge
                val badgeText = if (aiResult.isDemo) {
                    when (lang) {
                        com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "💡 JOY BEGLEITER (LOKALER / DEMO-MODUS)"
                        com.example.ui.localization.AppLanguageSupported.ENGLISH -> "💡 JOY COMPANION (LOCAL / DEMO MODE)"
                        com.example.ui.localization.AppLanguageSupported.ESPANOL -> "💡 COMPAÑERO JOY (MODO LOCAL / DEMOSTRACIÓN)"
                        com.example.ui.localization.AppLanguageSupported.ITALIANO -> "💡 ASSISTENTE JOY (MODALITÀ LOCALE / DEMO)"
                        com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "💡 COMPANHEIRO JOY (MODO DEMONSTRAÇÃO / LOCAL)"
                        com.example.ui.localization.AppLanguageSupported.CHINESE -> "💡 JOY 伴侣 (本地 / 演示模式)"
                        com.example.ui.localization.AppLanguageSupported.JAPANESE -> "💡 JOYアシスタント (ローカル / デモ)"
                        com.example.ui.localization.AppLanguageSupported.KOREAN -> "💡 JOY 동반자 (로컬 / 데모 모드)"
                        com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "💡 АССИСТЕНТ JOY (ЛОКАЛЬНЫЙ / ДЕМО-РЕЖИМ)"
                        com.example.ui.localization.AppLanguageSupported.ARABIC -> "💡 رفيق الغد (المستوى المحلي / العرض التوضيحي)"
                        else -> "💡 COMPAGNON JOY (MODE DÉMONSTRATION / LOCAL)"
                    }
                } else {
                    when (lang) {
                        com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "✨ JOY AI IN ECHTZEIT (UNTERSTÜTZT DURCH GEMINI)"
                        com.example.ui.localization.AppLanguageSupported.ENGLISH -> "✨ LIVE FROM JOY AI (POWERED BY GEMINI)"
                        com.example.ui.localization.AppLanguageSupported.ESPANOL -> "✨ EN VIVO DESDE JOY AI (IMPULSADO POR GEMINI)"
                        com.example.ui.localization.AppLanguageSupported.ITALIANO -> "✨ IN DIRETTA DA JOY AI (ALIMENTATO DA GEMINI)"
                        com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "✨ AO VIVO DA JOY AI (POWERED BY GEMINI)"
                        com.example.ui.localization.AppLanguageSupported.CHINESE -> "✨ 实时联机 JOY AI (由 GEMINI 强力驱动)"
                        com.example.ui.localization.AppLanguageSupported.JAPANESE -> "✨ リアルタイム搭载 JOY AI (POWERED BY GEMINI)"
                        com.example.ui.localization.AppLanguageSupported.KOREAN -> "✨ 실시간 JOY AI (GEMINI 작동)"
                        com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "✨ В ЖИВОМ РЕЖИМЕ С JOY AI (НА БАЗЕ GEMINI)"
                        com.example.ui.localization.AppLanguageSupported.ARABIC -> "✨ مباشر من JOY AI (مدعوم بواسطة GEMINI)"
                        else -> "✨ EN DIRECT DE JOY AI (PROPULSÉ PAR GEMINI)"
                    }
                }
                val badgeColor = if (aiResult.isDemo) "#E65100" else "#311B92"
                
                val badgePaint = Paint().apply {
                    color = Color.parseColor(badgeColor)
                    textSize = 7.5f
                    typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                    isAntiAlias = true
                }
                
                val badgeTextWidth = badgePaint.measureText(badgeText)
                cursor.canvas?.drawText(badgeText, cursor.width - cursor.margin - badgeTextWidth, cursor.currentY, badgePaint)
                cursor.moveDown(15f)

                // Summarized paragraph wrapper
                val widthLimit = cursor.width - cursor.margin * 2f
                val bodyPaint = Paint().apply {
                    color = Color.parseColor("#333333")
                    textSize = 8.5f
                    typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
                    isAntiAlias = true
                }
                
                drawMultilineText(aiResult.summary, cursor.margin, widthLimit, bodyPaint, cursor)
                cursor.moveDown(8f)

                // Itemized bullets
                aiResult.adviceList.forEach { advice ->
                    cursor.ensureSpace(12f)
                    cursor.canvas?.drawText("•", cursor.margin, cursor.currentY, boldPaint)
                    drawMultilineText(advice, cursor.margin + 10f, widthLimit - 10f, bodyPaint, cursor)
                    cursor.moveDown(4f)
                }
                
                cursor.moveDown(12f)
                // Divider
                cursor.canvas?.drawLine(cursor.margin, cursor.currentY, cursor.width - cursor.margin, cursor.currentY, linePaint)
                cursor.moveDown(15f)
            }

            // --- SECTION 5: TRANSACTIONS LIST TABLE ---
            cursor.ensureSpace(80f)
            val transactionsListTitle = when (lang) {
                com.example.ui.localization.AppLanguageSupported.ENGLISH -> "DETAILED TRANSACTIONS LIST"
                com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "DETAILLIERTE TRANSAKTIONSLISTE"
                com.example.ui.localization.AppLanguageSupported.ESPANOL -> "LISTA DE TRANSACCIONES DETALLADAS"
                com.example.ui.localization.AppLanguageSupported.ITALIANO -> "ELENCO DETTAGLIATO DELLE TRANSAZIONI"
                com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "LISTA DE TRANSAÇÕES DETALHADAS"
                com.example.ui.localization.AppLanguageSupported.CHINESE -> "交易明细清单"
                com.example.ui.localization.AppLanguageSupported.JAPANESE -> "取引詳細一覧"
                com.example.ui.localization.AppLanguageSupported.KOREAN -> "상세 거래 내역 리스트"
                com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "ПОДРОБНЫЙ СПИСОК ТРАНСАКЦИЙ"
                com.example.ui.localization.AppLanguageSupported.ARABIC -> "قائمة المعاملات التفصيلية"
                else -> "LISTE DES TRANSACTIONS DÉTAILLÉES"
            }
            cursor.canvas?.drawText(transactionsListTitle, cursor.margin, cursor.currentY, sectionHeadPaint)
            cursor.moveDown(15f)

            if (transactions.isEmpty()) {
                val noTransactionsLabel = when (lang) {
                    com.example.ui.localization.AppLanguageSupported.ENGLISH -> "No transactions registered this month."
                    com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "In diesem Monat wurden keine Transaktionen erfasst."
                    com.example.ui.localization.AppLanguageSupported.ESPANOL -> "No se registraron transacciones este mes."
                    com.example.ui.localization.AppLanguageSupported.ITALIANO -> "Nessuna transazione registrata questo mese."
                    com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "Nenhuma transação registrada este mês."
                    com.example.ui.localization.AppLanguageSupported.CHINESE -> "当月没有记录任何交易。"
                    com.example.ui.localization.AppLanguageSupported.JAPANESE -> "今月は取引が記録されていません。"
                    com.example.ui.localization.AppLanguageSupported.KOREAN -> "이번 달에 등록된 거래가 없습니다."
                    com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "За этот месяц трансакций не зарегистрировано."
                    com.example.ui.localization.AppLanguageSupported.ARABIC -> "لم يتم تسجيل أي معاملات هذا الشهر."
                    else -> "Aucune transaction enregistrée sous ce mois."
                }
                cursor.canvas?.drawText(noTransactionsLabel, cursor.margin, cursor.currentY, normalPaint)
                cursor.moveDown(15f)
            } else {
                // Table header background
                val headerHeight = 15f
                val tableHeaderPaint = Paint().apply {
                    color = Color.parseColor("#F5F5F7")
                    style = Paint.Style.FILL
                }
                cursor.canvas?.drawRect(cursor.margin, cursor.currentY - 10f, cursor.width - cursor.margin, cursor.currentY + headerHeight - 10f, tableHeaderPaint)

                // Render Table row headers
                val colDateX = cursor.margin + 5f
                val colTypeX = cursor.margin + 75f
                val colCatX = cursor.margin + 120f
                val colLabelX = cursor.margin + 250f
                val colAmountX = cursor.width - cursor.margin - 5f // Right aligned!

                val tableHeaderLabelPaint = Paint().apply {
                    color = Color.parseColor("#424242")
                    textSize = 8f
                    typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                    isAntiAlias = true
                }

                val headerDateLabel = when (lang) {
                    com.example.ui.localization.AppLanguageSupported.ENGLISH -> "Date"
                    com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "Datum"
                    com.example.ui.localization.AppLanguageSupported.ESPANOL -> "Fecha"
                    com.example.ui.localization.AppLanguageSupported.ITALIANO -> "Data"
                    com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "Data"
                    com.example.ui.localization.AppLanguageSupported.CHINESE -> "日期"
                    com.example.ui.localization.AppLanguageSupported.JAPANESE -> "日付"
                    com.example.ui.localization.AppLanguageSupported.KOREAN -> "날짜"
                    com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "Дата"
                    com.example.ui.localization.AppLanguageSupported.ARABIC -> "التاريخ"
                    else -> "Date"
                }

                val headerTypeLabel = when (lang) {
                    com.example.ui.localization.AppLanguageSupported.ENGLISH -> "Type"
                    com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "Typ"
                    com.example.ui.localization.AppLanguageSupported.ESPANOL -> "Tipo"
                    com.example.ui.localization.AppLanguageSupported.ITALIANO -> "Tipo"
                    com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "Tipo"
                    com.example.ui.localization.AppLanguageSupported.CHINESE -> "类型"
                    com.example.ui.localization.AppLanguageSupported.JAPANESE -> "種別"
                    com.example.ui.localization.AppLanguageSupported.KOREAN -> "분류"
                    com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "Тип"
                    com.example.ui.localization.AppLanguageSupported.ARABIC -> "النوع"
                    else -> "Type"
                }

                val headerCategoryLabel = when (lang) {
                    com.example.ui.localization.AppLanguageSupported.ENGLISH -> "Category"
                    com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "Kategorie"
                    com.example.ui.localization.AppLanguageSupported.ESPANOL -> "Categoría"
                    com.example.ui.localization.AppLanguageSupported.ITALIANO -> "Categoria"
                    com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "Categoria"
                    com.example.ui.localization.AppLanguageSupported.CHINESE -> "类别"
                    com.example.ui.localization.AppLanguageSupported.JAPANESE -> "カテゴリー"
                    com.example.ui.localization.AppLanguageSupported.KOREAN -> "카테고리"
                    com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "Категория"
                    com.example.ui.localization.AppLanguageSupported.ARABIC -> "الفئة"
                    else -> "Catégorie"
                }

                val headerLabelLabel = when (lang) {
                    com.example.ui.localization.AppLanguageSupported.ENGLISH -> "Description"
                    com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "Beschreibung"
                    com.example.ui.localization.AppLanguageSupported.ESPANOL -> "Descripción"
                    com.example.ui.localization.AppLanguageSupported.ITALIANO -> "Descrizione"
                    com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "Descrição"
                    com.example.ui.localization.AppLanguageSupported.CHINESE -> "名称"
                    com.example.ui.localization.AppLanguageSupported.JAPANESE -> "摘要"
                    com.example.ui.localization.AppLanguageSupported.KOREAN -> "내용"
                    com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "Описание"
                    com.example.ui.localization.AppLanguageSupported.ARABIC -> "الوصف"
                    else -> "Libellé"
                }

                val headerAmountLabel = when (lang) {
                    com.example.ui.localization.AppLanguageSupported.ENGLISH -> "Amount"
                    com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "Betrag"
                    com.example.ui.localization.AppLanguageSupported.ESPANOL -> "Monto"
                    com.example.ui.localization.AppLanguageSupported.ITALIANO -> "Importo"
                    com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "Valor"
                    com.example.ui.localization.AppLanguageSupported.CHINESE -> "金额"
                    com.example.ui.localization.AppLanguageSupported.JAPANESE -> "金額"
                    com.example.ui.localization.AppLanguageSupported.KOREAN -> "금액"
                    com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "Сумма"
                    com.example.ui.localization.AppLanguageSupported.ARABIC -> "المبلغ"
                    else -> "Montant"
                }

                cursor.canvas?.drawText(headerDateLabel, colDateX, cursor.currentY, tableHeaderLabelPaint)
                cursor.canvas?.drawText(headerTypeLabel, colTypeX, cursor.currentY, tableHeaderLabelPaint)
                cursor.canvas?.drawText(headerCategoryLabel, colCatX, cursor.currentY, tableHeaderLabelPaint)
                cursor.canvas?.drawText(headerLabelLabel, colLabelX, cursor.currentY, tableHeaderLabelPaint)

                val amountHeaderWidth = tableHeaderLabelPaint.measureText(headerAmountLabel)
                cursor.canvas?.drawText(headerAmountLabel, colAmountX - amountHeaderWidth, cursor.currentY, tableHeaderLabelPaint)
                cursor.moveDown(18f)

                // Render each row. Since transactions could be numerous, ensureSpace handles screen shifts.
                val maxRowsToDraw = transactions.take(120) // Limit to a reasonable size to avoid infinite loops or memory leak
                maxRowsToDraw.forEach { tx ->
                    cursor.ensureSpace(15f)

                    // Get localized category name using UiUtils.getLocalizedCategory!
                    val catDisplayString = UiUtils.getLocalizedCategory(tx.category, t)
                    val categoryDisplay = if (!tx.customCategory.isNullOrBlank()) {
                        "$catDisplayString — ${tx.customCategory}"
                    } else {
                        catDisplayString
                    }

                    // Alignments & Truncation limiting variables
                    val formattedDate = UiUtils.formatDate(tx.dateTimestamp)
                    val formattedAmt = UiUtils.formatCurrency(tx.amount)
                    val txType = when (tx.type) {
                        "INCOME" -> when (lang) {
                            com.example.ui.localization.AppLanguageSupported.ENGLISH -> "Inc."
                            com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "Einn."
                            com.example.ui.localization.AppLanguageSupported.ESPANOL -> "Ing."
                            com.example.ui.localization.AppLanguageSupported.ITALIANO -> "Ent."
                            com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "Rec."
                            com.example.ui.localization.AppLanguageSupported.CHINESE -> "收入"
                            com.example.ui.localization.AppLanguageSupported.JAPANESE -> "収入"
                            com.example.ui.localization.AppLanguageSupported.KOREAN -> "수입"
                            com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "Дох."
                            com.example.ui.localization.AppLanguageSupported.ARABIC -> "دخل"
                            else -> "Rev."
                        }
                        "EXPENSE" -> when (lang) {
                            com.example.ui.localization.AppLanguageSupported.ENGLISH -> "Exp."
                            com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "Ausg."
                            com.example.ui.localization.AppLanguageSupported.ESPANOL -> "Gas."
                            com.example.ui.localization.AppLanguageSupported.ITALIANO -> "Sp."
                            com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "Des."
                            com.example.ui.localization.AppLanguageSupported.CHINESE -> "支出"
                            com.example.ui.localization.AppLanguageSupported.JAPANESE -> "支出"
                            com.example.ui.localization.AppLanguageSupported.KOREAN -> "지출"
                            com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "Расх."
                            com.example.ui.localization.AppLanguageSupported.ARABIC -> "صرف"
                            else -> "Dép."
                        }
                        "SAVING" -> when (lang) {
                            com.example.ui.localization.AppLanguageSupported.ENGLISH -> "Sav."
                            com.example.ui.localization.AppLanguageSupported.DEUTSCH -> "Spar."
                            com.example.ui.localization.AppLanguageSupported.ESPANOL -> "Aho."
                            com.example.ui.localization.AppLanguageSupported.ITALIANO -> "Ris."
                            com.example.ui.localization.AppLanguageSupported.PORTUGUES -> "Pou."
                            com.example.ui.localization.AppLanguageSupported.CHINESE -> "储蓄"
                            com.example.ui.localization.AppLanguageSupported.JAPANESE -> "貯蓄"
                            com.example.ui.localization.AppLanguageSupported.KOREAN -> "저축"
                            com.example.ui.localization.AppLanguageSupported.RUSSIAN -> "Сбер."
                            com.example.ui.localization.AppLanguageSupported.ARABIC -> "ادخار"
                            else -> "Épa."
                        }
                        else -> tx.type
                    }

                    // Amounts color theme
                    val txColor = when (tx.type) {
                        "INCOME" -> "#2E7D32"
                        "EXPENSE" -> "#C62828"
                        else -> "#1565C0"
                    }
                    val rowAmountPaint = Paint().apply {
                        color = Color.parseColor(txColor)
                        textSize = 8f
                        typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
                        isAntiAlias = true
                    }

                    val rowNormalPaint = Paint().apply {
                        color = Color.parseColor("#424242")
                        textSize = 8f
                        isAntiAlias = true
                    }

                    // Category & description wrapping limits
                    val catText = truncateTextToWidth(categoryDisplay, 120f, rowNormalPaint)
                    val labelText = truncateTextToWidth(tx.label, 160f, rowNormalPaint)

                    cursor.canvas?.drawText(formattedDate, colDateX, cursor.currentY, rowNormalPaint)
                    cursor.canvas?.drawText(txType, colTypeX, cursor.currentY, rowNormalPaint)
                    cursor.canvas?.drawText(catText, colCatX, cursor.currentY, rowNormalPaint)
                    cursor.canvas?.drawText(labelText, colLabelX, cursor.currentY, rowNormalPaint)

                    val amtWidth = rowAmountPaint.measureText(formattedAmt)
                    cursor.canvas?.drawText(formattedAmt, colAmountX - amtWidth, cursor.currentY, rowAmountPaint)
                    
                    // Tiny bottom line separator between rows
                    val rowUnderlinePaint = Paint().apply {
                        color = Color.parseColor("#EEEEEE")
                        strokeWidth = 0.5f
                        style = Paint.Style.STROKE
                    }
                    cursor.canvas?.drawLine(cursor.margin, cursor.currentY + 3f, cursor.width - cursor.margin, cursor.currentY + 3f, rowUnderlinePaint)

                    cursor.moveDown(14f)
                }
            }

            cursor.finish()

            // Save inside context cache folder or cache system
            val cacheDir = context.cacheDir
            val joyReportDir = File(cacheDir, "joy_reports").apply { mkdirs() }
            val formattedDateName = SimpleDateFormat("yyyy-MM", Locale.getDefault()).format(Date())
            val pdfFile = File(joyReportDir, "budget-joy-$formattedDateName.pdf")

            val outStream = FileOutputStream(pdfFile)
            pdfDocument.writeTo(outStream)
            outStream.flush()
            outStream.close()

            Log.d(tag, "Successfully created budget report PDF at: ${pdfFile.absolutePath}")
            return pdfFile
        } catch (e: Exception) {
            Log.e(tag, "Fail during PDF formatting generation", e)
            return null
        } finally {
            pdfDocument.close()
        }
    }

    /**
     * Splits paragraph text in small pieces to support wrap block printing.
     */
    private fun drawMultilineText(
        text: String,
        x: Float,
        widthLimit: Float,
        paint: Paint,
        cursor: PageCursor,
        lineSpacing: Float = 11f
    ) {
        val words = text.split(" ")
        var currentLine = StringBuilder()
        for (word in words) {
            val testLine = if (currentLine.isEmpty()) word else "${currentLine} $word"
            val testWidth = paint.measureText(testLine)
            if (testWidth > widthLimit) {
                cursor.ensureSpace(lineSpacing)
                cursor.canvas?.drawText(currentLine.toString(), x, cursor.currentY, paint)
                cursor.moveDown(lineSpacing)
                currentLine = StringBuilder(word)
            } else {
                currentLine = StringBuilder(testLine)
            }
        }
        if (currentLine.isNotEmpty()) {
            cursor.ensureSpace(lineSpacing)
            cursor.canvas?.drawText(currentLine.toString(), x, cursor.currentY, paint)
            cursor.moveDown(lineSpacing)
        }
    }

    /**
     * Helps truncate text exactly matching limits.
     */
    private fun truncateTextToWidth(text: String, widthLimit: Float, paint: Paint): String {
        val ellipsis = "..."
        if (paint.measureText(text) <= widthLimit) return text
        var truncated = text
        while (truncated.isNotEmpty() && paint.measureText("$truncated$ellipsis") > widthLimit) {
            truncated = truncated.dropLast(1)
        }
        return if (truncated.isEmpty()) ellipsis else "$truncated$ellipsis"
    }
}
